### ISSUE TITLE
The bib cannot be compiled

### ISSUE THREAD

**Issue by zhtaoxiang** [zhehaowang/UCLA-CS211#1]
1. I added reference into .bib file
2. I use \cite to cite the article
3. run pdflatex
4. the output pdf cannot cite the article correctly.

**Comment by zhehaowang** [comment]
Alright added bib reference; please use proposal/proposal.bib

To update bib and the output pdf, please do:
pdflatex proposal
bibtex proposal
pdflatex proposal
